import { randomBytes } from 'node:crypto';

import { ChainfileDefinition, Container } from 'chainfile';
import { synthEnv } from 'chainfile/environment';
import { validate } from 'chainfile/schema';
import yaml from 'js-yaml';

import { version } from './package.json';

/**
 * Synthesize a ChainfileDefinition into `docker.*.yml` & `.env` files.
 */
export class Synthesizer {
  private readonly definition: ChainfileDefinition;
  /**
   * A random deploymentId is generated for each synthesizer to uniquely the lifetime of a deployment.
   */
  public readonly deploymentId: string = randomBytes(8).toString('hex');

  constructor(definition: ChainfileDefinition | any) {
    validate(definition);
    this.definition = definition;
  }

  public synthEnv(): string {
    return Object.entries({
      ...synthEnv(this.definition.environment ?? {}),
      CHAINFILE_DEPLOYMENT_ID: this.deploymentId,
    })
      .map(([key, value]) => `${key}=${value}`)
      .join('\n');
  }

  public synthCompose(): string {
    return [
      `# Generated by chainfile-docker, do not edit manually.`,
      `# Chainfile Version: ${version}`,
      `# Definition ID: ${this.definition.id}`,
      `# Definition Name: ${this.definition.name}`,
      `# Definition CAIP-2: ${this.definition.caip2}`,
      '',
      yaml.dump(
        {
          name: this.definition.id.replaceAll(/[^a-z0-9_-]/g, '_'),
          services: {
            ...this.createChainfileAgent(),
            ...this.createContainers(),
          },
          networks: {
            chainfile: {},
          },
          volumes: {
            chainfile: {},
          },
        },
        {
          lineWidth: 120,
        },
      ),
    ].join('\n');
  }

  private createChainfileAgent(): Record<'chainfile-agent', object> {
    const definitionJson = JSON.stringify({
      ...this.definition,
      $schema: undefined,
    }).replaceAll('$', '$$$');

    const EnvironmentMapping = Object.keys(this.definition.environment ?? {}).reduce(
      (env, key) => {
        env[`CHAINFILE_ENVIRONMENT_${key}`] = `$\{${key}}`;
        return env;
      },
      {} as Record<string, string>,
    );

    return {
      'chainfile-agent': {
        container_name: 'chainfile-agent-${CHAINFILE_DEPLOYMENT_ID}',
        image: `ghcr.io/vetumorg/chainfile-agent:${version}`,
        ports: ['0:1503'],
        environment: {
          // Docker compose automatically evaluate environment literals here
          CHAINFILE_DEFINITION_JSON: definitionJson,
          CHAINFILE_DEPLOYMENT_ID: '${CHAINFILE_DEPLOYMENT_ID}',
          ...EnvironmentMapping,
        },
        volumes: [
          {
            type: 'volume',
            source: 'chainfile',
            target: '/var/chainfile',
          },
        ],
        networks: {
          chainfile: {},
        },
      },
    };
  }

  private createContainers(): Record<string, object> {
    // TODO: resources (cpu, memory) is not supported yet for docker-compose
    //  https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
    //  I'm not sure if we should since docker-compose typically runs on a single machine
    //  and utilizes the host's resources.
    //  Which limits its usefulness in orchestration when placement is not a concern.
    //  Adding them would make the compose hard limit the resources of the host even if the host
    //  has more resources available.

    function createPorts(container: Container): string[] {
      return Object.values(container.endpoints).map((endpoint) => {
        // TODO: Support Binding P2P Port Statically
        return `0:${endpoint.port}`;
      });
    }

    interface Volume {
      type: 'volume';
      source?: string;
      target: string;
    }

    function createVolumes(container: Container): Volume[] {
      const volumes: Volume[] = [
        {
          type: 'volume',
          source: 'chainfile',
          target: '/var/chainfile',
        },
      ];

      container.volumes?.persistent?.paths.forEach((path) => {
        volumes.push({
          type: 'volume',
          target: path,
        });
      });

      container.volumes?.ephemeral?.paths.forEach((path) => {
        volumes.push({
          type: 'volume',
          target: path,
        });
      });

      return volumes;
    }

    return Object.entries(this.definition.containers).reduce(
      (services, [name, container]) => {
        services[name] = {
          container_name: `${name}-$\{CHAINFILE_DEPLOYMENT_ID}`,
          image: container.image,
          command: container.command,
          environment: Object.entries(container.environment ?? {}).reduce(
            (env, [key, value]) => {
              return {
                ...env,
                [key]: typeof value === 'string' ? value : `$\{${value.key}}`,
              };
            },
            {} as Record<string, string>,
          ),
          ports: createPorts(container),
          volumes: createVolumes(container),
          networks: {
            chainfile: {},
          },
        };
        return services;
      },
      {} as Record<string, object>,
    );
  }
}
